### ISSUE TITLE
renderPdf(texDirectory.getAbsolutePath(), texFile) is duplicated

### ISSUE THREAD

**Issue by pandarun** [vsfexperts/LaTeX#5]
Thank you for your project, I've used it for reference!

Probably found a typo:

LatexRenderJob runInternal method runs twice as long

**Comment by alexanderpilch** [comment]
LaTeX has to be run multiple times, if you're e.g. using table of contents/cross references in your documents. [Latexmk](https://mg.readthedocs.io/latexmk.html) (instead of pdflatex) is more efficient and taking care of that, but you'll have to install perl on your system as well. We're just running the pdf generation twice in order to take care of that. This will slow down the rendering process, but it's a simple hack to get correct results. If you aren't using references, you can also remove the 2nd invocation in order to be more efficient. The assumption is basically, that there will be more reads than writes so that the duration of the rendering process doesn't matter that much.
