### ISSUE TITLE
Clean procedure

### ISSUE THREAD

**Issue by masics** [vsfexperts/LaTeX#6]
After 1000's of render requests there must be a lot of abandoned tex and pdf files still stored. Is there an easy way to clean them up? This is important especially for the docker.

**Comment by alexanderpilch** [comment]
The renderer will cleanup the temporary folder, see 

https://github.com/vsfexperts/LaTeX/blob/544b824d3ab0b121cd8c54b34a953f28a9bdc082/latex-renderer/src/main/java/de/vsfexperts/latex/renderer/LatexRenderJob.java#L36-L46

The archived output (tex, pdf)) is stored in the archive directory/volume. The size of this folder will increase unless you're deleting the archived output periodically. You could use some [bind mount](https://4sysops.com/archives/introduction-to-docker-bind-mounts-and-volumes/) and clean the folder via some external script periodically. The render output is immutable, so it makes sense to keep it on the filesystem, so that clients just have to store the uuid in order to identify/retrieve it. The tex file is just in there for debugging purposes (e.g. if the pdf is showing some unexpected layout issues due to unexpected input data).
